name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Definir JDK
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven
      - name: build do projeto
        run: mvn -B clean package --file pom.xml

      - name: docker build
        run: docker build -t gustosilva/enum-strategy .

      - name: docker login
        env:
          DOCKER_USER: ${{secrets.DOCKER_USER}}
          DOCKER_TOKEN: ${{secrets.DOCKER_TOKEN}}
        run: docker login -u $DOCKER_USER -p $DOCKER_TOKEN

      - name: docker tag
        run: docker tag $(docker images --filter=reference='gustosilva/enum-strategy' --format "{{.ID}}") gustosilva/enum-strategy

      - name: docker push
        run: docker push gustosilva/enum-strategy

      - name: docker sync
        uses: ms-jpq/sync-dockerhub-readme@v1
        with:
          username: ${{secrets.DOCKER_USER}}
          password: ${{secrets.DOCKER_TOKEN}}
          repository: gustosilva/enum-strategy
          readme: "./README.md"

      - name: docker logout
        run: docker logout